name: "Analyze"

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          
      - name: "Add dart support"
        uses: dart-lang/setup-dart@v1

      - name: "Install dependencies"
        run: dart pub get

      - name: "Run static analysis"
        run: "dart analyze"

      - name: "Check outdated packages"
        run: "dart pub outdated"

  